student_name=input("enter your name:")
student_age=int(input("enter your age:"))
maths=float(input("maths mark:"))
science=float(input("science mark:"))
english=float(input("english mark:"))
total_mark= maths + science + english
average_mark=total_mark/3
print("\n"+ "="*30)
print("STUDENT RESULT")
print( "="*30)
print(f"student name:{student_name}")
print(f"student age:{student_age}")
print("marks:")
print(f"maths mark:{maths}")
print(f"science mark:{science}")
print(f"english mark:{english}")
print("-"*35)
print(f"total mark:{total_mark}")
print(f"average mark:{average_mark}")
